### ISSUE TITLE
Superfluous slashes in icon URLs

### ISSUE THREAD

**Issue by pascalroget** [wonoly/icon-scraper#1]
Hi,

In Scraper.php, you are doing this:

`// Make sure the href is an absolute URL.
if ($href && filter_var($href, FILTER_VALIDATE_URL) === false) {
    $href = $url . '/' . $href; //Todo: Improve this
}`

This fails in some cases, for example, consider
$url = 'https//www.cnn.com';
$href = '/favicon.ie9.ico';

The resulting icon URL would be `https://www.cnn.com//favicon.ie9.ico`

I believe an additional case should be written for relative URLs as FILTER_VALIDATE_URL is not enough to confirm an absolute URL.

What do you think?

**Comment by mauro-balades** [comment]
Hi! sorry for not responding.
This package is not maintained any more. Sorry. You can create a fork and fix it if you want.
